### ISSUE TITLE
KeyError: 'database'

### ISSUE THREAD

**Issue by cdhas52** [redhat-chaos/cerberus#158]
I am getting the below error in after deployed in kubernetes Cluster.              

 _                         
  ___ ___ _ __| |__   ___ _ __ _   _ ___ 
 / __/ _ \ '__| '_ \ / _ \ '__| | | / __|
| (_|  __/ |  | |_) |  __/ |  | |_| \__ \
 \___\___|_|  |_.__/ \___|_|   \__,_|___/
                                         

Traceback (most recent call last):
  File "start_cerberus.py", line 516, in <module>
    main(options.cfg)
  File "start_cerberus.py", line 87, in main
    database_path = config["database"].get("database_path", "/tmp/cerberus.db")
KeyError: 'database'

**Comment by paigerube14** [comment]
@cdhas52 This is a section in the cerberus config/config.yaml file 
See [here](https://github.com/chaos-kubox/cerberus/blob/a2ee75d0665fe04c9798cfe93bc64b013325ce79/config/config.yaml#L52 ) for example.

I noticed it is not in the[ kuberenetes.yaml](https://github.com/chaos-kubox/cerberus/blob/main/config/kubernetes_config.yaml) file. Is that the configuration file you were using?

**Comment by chaitanyaenr** [comment]
Hi @cdhas52, closing the issue as the database section is now part of Kubernetes config. Please feel free to reopen if we are still hitting the issue and we are more than happy to help.
