### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by paigerube14** [redhat-chaos/cerberus#194]
https://github.com/redhat-chaos/cerberus/actions/runs/4058914012
```
      File "/tmp/pip-build-6j7gpd9m/aiohttp/aiohttp/hdrs.py", line 8, in <module>
        from multidict import istr
    ModuleNotFoundError: No module named 'multidict'
```

**Comment by paigerube14** [comment]
https://pypi.org/project/slackclient/

`This [slackclient](https://pypi.org/project/slackclient/) PyPI project is in maintenance mode now and [slack-sdk](https://pypi.org/project/slack-sdk/) project is the successor. The v3 SDK provides more functionalities such as Socket Mode, OAuth flow module, SCIM API, Audit Logs API, better asyncio support, retry handlers, and many more.`

Trying to add that module instead and build locally before pushing

**Comment by chaitanyaenr** [comment]
Closing as the issue should now be fixed. Thanks to @paigerube14!
